name: 'Deploy Website'
description: 'Deploy website to Netlify'
inputs:
  netlify-site-id:
    description: 'Netlify site ID'
    required: true
  netlify-auth-token:
    description: 'Netlify auth token'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: website
        path: artifacts

    - name: Display structure of downloaded files
      run: |
        cd artifacts
        ls -R

    - name: Unzip
      run: |
        cd artifacts
        mkdir -p website
        unzip website.zip -d website

    - name: Deploy website to Netlify
      run: |
        npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir artifacts/website
