name: 'Publish to Homebrew'
description: 'Publish the MacOS package to Homebrew'
inputs:
  release-version:
    description: 'The release version'
    required: true
  release-tag:
    description: 'The release tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Append the msi file to release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          algokit-lora_*.dmg
        tag_name: ${{ inputs.release-tag }}
        prerelease: ${{ contains(inputs.release-tag, 'beta') }}
