export const assetDetailsLabel = 'Asset Details'
export const assetIdLabel = 'Asset ID'
export const assetNameLabel = 'Name'
export const assetDescriptionLabel = 'Description'
export const assetUnitNameLabel = 'Unit'
export const assetDecimalsLabel = 'Decimals'
export const assetTotalSupplyLabel = 'Total Supply'
export const assetMetadataHashLabel = 'Metadata Hash'
export const assetDefaultFrozenLabel = 'Default Frozen'
export const assetUrlLabel = 'URL'
export const assetMediaLabel = 'Asset Media'

export const assetAddressesLabel = 'Asset Addresses'
export const assetCreatorLabel = 'Creator'
export const assetManagerLabel = 'Manager'
export const assetReserveLabel = 'Reserve'
export const assetFreezeLabel = 'Freeze'
export const assetClawbackLabel = 'Clawback'

export const assetTraitsLabel = 'Asset Traits'

export const assetMetadataLabel = 'Asset Metadata'

export const assetActivityLabel = 'Activity'
export const assetLiveTransactionsTabId = 'live-transactions'
export const assetLiveTransactionsTabLabel = 'Live Transactions'
export const assetHistoricalTransactionsTabId = 'historical-transactions'
export const assetHistoricalTransactionsTabLabel = 'Historical Transactions'
