export const editAppInterfacePageTitle = 'Edit App Interface'
export const appInterfaceNotFoundMessage = 'Application Interface not found'
export const applicationInvalidIdMessage = 'Application Id is invalid'
export const appInterfaceFailedToLoadMessage = 'Application Interface failed to load'
export const updateAppPageTitle = 'Update App'
