export const accountActivityLabel = 'Activity'
export const accountAssetLabel = 'Assets'
export const accountApplicationLabel = 'Applications'

export const accountLiveTransactionsTabLabel = 'Live Transactions'
export const accountHistoricalTransactionsTabLabel = 'Historical Transactions'
export const accountHeldAssetsTabLabel = 'Held'
export const accountCreatedAssetsTabLabel = 'Created'
export const accountOptedAssetsTabLabel = 'Opted'
export const accountCreatedApplicationsTabLabel = 'Created'
export const accountOptedApplicationsTabLabel = 'Opted'

export const accountLiveTransactionsTabId = 'live-transactions'
export const accountHistoricalTransactionsTabId = 'historical-transactions'
export const accountHeldAssetsTabId = 'held-assets'
export const accountCreatedAssetsTabId = 'created-assets'
export const accountOptedAssetsTabId = 'opted-assets'
export const accountCreatedApplicationsTabId = 'created-applications'
export const accountOptedApplicationsTabId = 'opted-applications'

export const accountInformationLabel = 'Account Information'
export const accountAddressLabel = 'Address'
export const accountNfdLabel = 'NFD'
export const accountBalanceLabel = 'Balance'
export const accountMinBalanceLabel = 'Min Balance'
export const accountAssetsHeldLabel = 'Held assets'
export const accountAssetsCreatedLabel = 'Created assets'
export const accountAssetsOptedInLabel = 'Opted assets'
export const accountApplicationsCreatedLabel = 'Created applications'
export const accountApplicationsOptedInLabel = 'Opted applications'
export const accountRekeyedToLabel = 'Rekeyed to'
