name: 'Build for Mac'
description: 'Build for Mac'
inputs:
  production-release:
    description: 'Whether this is a production release'
    required: true
  release-version:
    description: 'The release version'
    required: true
  release-tag:
    description: 'The release tag'
    required: true
  crabnebula-release-id:
    description: 'The CrabNebula release ID'
    required: true
  apple-certificate:
    description: 'The Apple certificate'
    required: true
  apple-certificate-password:
    description: 'The Apple certificate password'
    required: true
  keychain-password:
    description: 'The keychain password'
    required: true
  apple-id:
    description: 'The Apple ID'
    required: true
  apple-password:
    description: 'The Apple password'
    required: true
  apple-team-id:
    description: 'The Apple team ID'
    required: true
  tauri-signing-private-key:
    description: 'The Tauri signing private key'
    required: true
  tauri-signing-private-key-password:
    description: 'The Tauri signing private key password'
    required: true
  tauri-signing-public-key:
    description: 'The Tauri signing public key'
    required: true
  crabnebula-org-name:
    description: 'The CrabNebula org name'
    required: true
  crabnebula-app-name:
    description: 'The CrabNebula app name'
    required: true
  crabnebula-api-key:
    description: 'The CrabNebula API key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Import Apple Developer Certificate
      env:
        APPLE_CERTIFICATE: ${{ inputs.apple-certificate }}
        APPLE_CERTIFICATE_PASSWORD: ${{ inputs.apple-certificate-password }}
        KEYCHAIN_PASSWORD: ${{ inputs.keychain-password }}
      shell: bash
      run: |
        echo $APPLE_CERTIFICATE | base64 --decode > certificate.p12
        security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
        security set-keychain-settings -t 3600 -u build.keychain
        security import certificate.p12 -k build.keychain -P "$APPLE_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain
        security find-identity -v -p codesigning build.keychain

    - name: Verify Certificate
      shell: bash
      run: |
        CERT_INFO=$(security find-identity -v -p codesigning build.keychain | grep "Developer ID Application")
        CERT_ID=$(echo "$CERT_INFO" | awk -F'"' '{print $2}')
        echo "CERT_ID=$CERT_ID" >> $GITHUB_ENV
        echo "Certificate imported."

    - name: Setup tauri.conf.json
      if: ${{ inputs.release-version != '' }}
      run: |
        sed -i '' "s/\"version\": \"0.0.0\"/\"version\": \"${{ inputs.release-version }}\"/g" "src-tauri/tauri.conf.json"
        sed -i '' "s/\"createUpdaterArtifacts\": false/\"createUpdaterArtifacts\": true/g" "src-tauri/tauri.conf.json"
        sed -i '' "s/CN_ORG_NAME/${{ inputs.crabnebula-org-name }}/g" "src-tauri/tauri.conf.json"
        sed -i '' "s/CN_APP_NAME/${{ inputs.crabnebula-app-name }}/g" "src-tauri/tauri.conf.json"
        sed -i '' "s/CN_CHANNEL/${{ inputs.production-release != 'true' && '?channel=beta' || '' }}/g" "src-tauri/tauri.conf.json"
        sed -i '' "s/TAURI_SIGNING_PUBLIC_KEY/${{ inputs.tauri-signing-public-key }}/g" "src-tauri/tauri.conf.json"
      shell: bash

    - name: Build tauri app
      run: |
        npm run tauri build
      shell: bash
      env:
        APPLE_CERTIFICATE: ${{ inputs.apple-certificate }}
        APPLE_CERTIFICATE_PASSWORD: ${{ inputs.apple-certificate-password }}
        APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}
        APPLE_ID: ${{ inputs.apple-id }}
        APPLE_PASSWORD: ${{ inputs.apple-password }}
        APPLE_TEAM_ID: ${{ inputs.apple-team-id }}
        TAURI_SIGNING_PRIVATE_KEY: ${{ inputs.tauri-signing-private-key }}
        TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ inputs.tauri-signing-private-key-password }}

    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: |
          src-tauri/target/release/bundle/dmg/algokit-lora_*.dmg
        tag_name: ${{ inputs.release-tag }}
        prerelease: ${{ inputs.production-release != 'true' }}

    - name: Upload artifacts to CrabNebula
      uses: crabnebula-dev/cloud-release@v0.2.0
      with:
        command: release upload "${{ inputs.crabnebula-org-name }}/${{ inputs.crabnebula-app-name }}" --framework tauri ${{ inputs.production-release != 'true' && '--channel beta' || '' }}
        api-key: ${{ inputs.crabnebula-api-key }}
