name: 'Build for Windows'
description: 'Build for Windows'
inputs:
  release-version:
    description: 'The release version'

runs:
  using: 'composite'
  steps:
    #  TODO: set up signing certs here when releasing to production
    - name: install dependencies (windows only)
      if: matrix.platform == 'windows-latest'
      shell: bash
      env:
        BEFORE_BUNDLE_COMMAND: echo "BEFORE_BUNDLE_COMMAND is working!"
      run: |
        cd "$GITHUB_WORKSPACE"
        cat './src-tauri/tauri.conf.json' | jq '.build += {"beforeBundleCommand": env.BEFORE_BUNDLE_COMMAND}' > './src-tauri/temp.json' && mv './src-tauri/temp.json' './src-tauri/tauri.conf.json'
        cargo install trusted-signing-cli

    - name: Build tauri app
      run: |
        npm run tauri build
      shell: bash
