export const applicationDetailsLabel = 'Application Details'
export const applicationIdLabel = 'Application ID'
export const applicationNameLabel = 'Application Name'
export const applicationCreatorAccountLabel = 'Creator'
export const applicationAccountLabel = 'Account'
export const applicationGlobalStateByteLabel = 'Global State Byte'
export const applicationGlobalStateUintLabel = 'Global State Uint'
export const applicationLocalStateByteLabel = 'Local State Byte'
export const applicationLocalStateUintLabel = 'Local State Uint'

export const applicationProgramsLabel = 'Application Programs'
export const applicationApprovalProgramLabel = 'Approval Program'
export const applicationClearStateProgramLabel = 'Clear State Program'
export const applicationApprovalProgramTabsListAriaLabel = 'View Application Approval Program Tabs'
export const applicationClearStateProgramTabsListAriaLabel = 'View Application Clear State Program Tabs'

export const applicationStateLabel = 'State'
export const applicationGlobalStateLabel = 'Global'
export const applicationGlobalStateTabId = 'global-state'
export const applicationLocalStateLabel = 'Local'
export const applicationLocalStateTabId = 'local-state'
export const applicationBoxesLabel = 'Box'
export const applicationBoxesTabId = 'boxes'

export const applicationBoxNameLabel = 'Name'
export const applicationBoxValueLabel = 'Value'

export const applicationTransactionsLabel = 'Activity'
export const applicationLiveTransactionsTabId = 'live-transactions'
export const applicationLiveTransactionsTabLabel = 'Live Transactions'
export const applicationHistoricalTransactionsTabId = 'historical-transactions'
export const applicationHistoricalTransactionsTabLabel = 'Historical Transactions'

export const applicationAbiMethodDefinitionsLabel = 'ABI Methods'

export const enterAddressToViewLocalStateMessage = 'Enter an address to view local state.'
export const failedToLoadLocalStateMessage = 'Failed to load local state.'
export const invalidAddressForLocalStateMessage = 'Invalid address or NFD.'
