export const contractNameLabel = 'Contract Name'
export const methodsLabel = 'Methods'
export const appIdLabel = 'App ID'
export const createAppInterfaceLabel = 'Create App Interface'
export const deleteAppInterfaceLabel = 'Delete App Interface'
export const deployAppLabel = 'Deploy new'
export const deployButtonLabel = 'Deploy'
