name: PR checks

on:
  pull_request:
    branches: '**'

permissions: {}

jobs:
  pr-checks:
    name: Run PR checks
    uses: makerxstudio/shared-config/.github/workflows/node-ci.yml@main
    permissions:
      contents: read
      packages: read
    with:
      working-directory: .
      node-version: 20.x
      audit-script: npm run audit
      compile-script: npm run check-types
      test-script: npm run test
      run-build: false
      pre-test-script: |
        pipx install algokit
        algokit localnet start
        npx --yes wait-on tcp:4001 -t 30000
